### ISSUE TITLE
Add special support for cover images.

### ISSUE THREAD

**Issue by Vagr9K** [Vagr9K/gatsby-material-starter#10]

**Comment by spences10** [comment]
Can you add cover images from within the post folder?

**Comment by Vagr9K** [comment]
Not currently.
`gatsby-remark-copy-linked-files` only copies files linked in Markdown, not in the frontmatter.
You'll have to place your covers into the `static` directory, and then link to the URL.

**Comment by halkeye** [comment]
Have you looked into this at all? I was poking around at seeing if i could make the sharp plugin generate something, but i ran into a snag with my cover url format and havn't gone back to the sample posts yet.

**Comment by Vagr9K** [comment]
Didn't had time unfortunately.
But as of right now, the easiest route seems to be `gatsby-images`.
