### ISSUE TITLE
`postDefaultCategoryID` is not obeyed.

### ISSUE THREAD

**Issue by MrJoy** [Vagr9K/gatsby-material-starter#22]
```
    if (!post.id) {
      post.category_id = config.postDefaultCategoryID;
    }
```

This appears to be a copy-paste error from the block immediately above (which sets `post.id` if it's not already set).  As such, the conditional behavior here will never be exercised.

I believe you meant:

```
    if (!post.category_id) {
      post.category_id = config.postDefaultCategoryID;
    }
```

**Comment by Vagr9K** [comment]
Thanks for noticing! Fixed!
