### ISSUE TITLE
Error when leaving the pathPrefix empty

### ISSUE THREAD

**Issue by appsolut-jahn** [Vagr9K/gatsby-material-starter#23]
I'm running the application on a root Domain, so no pathPrefix is needed. But an empty pathPrefix field in SiteConfig results in a build error message like "ValidationError: child "pathPrefix" fails because ["pathPrefix" is not allowed to be empty]". How to deal with this?

**Comment by Vagr9K** [comment]
Use `pathPrefix: "/"`.
Empty `pathPrefix` breaks gatsby compilation process.
