### ISSUE TITLE
FacebookShareButton warning: title is a deprecated prop. Use "quote" instead.

### ISSUE THREAD

**Issue by rickyjanuari** [Vagr9K/gatsby-material-starter#25]
FacebookShareButton warning: title is a deprecated prop. Use "quote" instead.

when npm run build:gh

how to fix?

**Comment by Vagr9K** [comment]
Seems like Facebook API has changed.
It's not a fatal warning. 

I don't have time to fix it myself right now. Try taking a look at Facebook API for buttons. Maybe you can fix it yourself.

**Comment by Neitsch** [comment]
For reference:
nygardk/react-share#93
nygardk/react-share#96

Simply remove the attributes from the FacebookShareButton.
