### ISSUE TITLE
Nested gatsby-material-starter folders under static folder

### ISSUE THREAD

**Issue by smerth** [Vagr9K/gatsby-material-starter#27]
I just cloned the repo and did not modify any files.  I was working through the file hierarchy to see how the app is put together and I found that under the static folder there are nested gatsby-material-starter folders (one nested inside another) 

In vs-code I gave up drilling down into the gatsby-material-starter folder it seems to go on forever.... I'm not sure how gatsby-material-starter folder is populated with the gatsby-material-starter alias, the logo folder, and the robot file.   If this is done programatically, it looks like some kind of loop is just building out this file tree forever....

**Comment by Vagr9K** [comment]
It's a self link.
See `gatsby-material-starter` in https://github.com/Vagr9K/gatsby-material-starter/tree/master/static.

Well, it's a hack to make testing before deployment easier.
You can totally remove it in your local website repo.

**Comment by smerth** [comment]
Ah! Thanks for that link and explanation.  And thanks for the project!

**Comment by Vagr9K** [comment]
👍
