### ISSUE TITLE
Disqus Not Working

### ISSUE THREAD

**Issue by btotharye** [Vagr9K/gatsby-material-starter#31]
I can't get the disqus commenting to work.  I have gone into my settings and added my domain geekedoutsolutions.com and updated the config file to what I believe is right.  Any chance you know what is happening?

https://www.geekedoutsolutions.com

code is at https://github.com/Geeked-Out-Solutions/blog

my short name should be geeked-out-solutions

**Comment by DanielDwyerPersonal** [comment]
how did you fix your error @btotharye? thanks

**Comment by btotharye** [comment]
I gave up on Gatsby and went with Jekyll :(
