### ISSUE TITLE
Stripped down version?

### ISSUE THREAD

**Issue by erichodges** [Vagr9K/gatsby-material-starter#32]
Hi Vagr9K,

If you or someone else has any time, I'm interested in a basic gatsby/material starter that just has a navbar at the top with a link to another page, maybe one content component in the main part of the page and a footer. This would give me a better idea of using gatsby/material-md without trying to strip out all of the blog content of this starter. Hope you don't mind me contacting you here, I was not sure where to write you. 

Best,
Eric

**Comment by Vagr9K** [comment]
Hi Eric,

Just remove PostListing component from this [line](https://github.com/Vagr9K/gatsby-material-starter/blob/master/src/pages/index.jsx#L17) and maybe remove the GraphQL queries.

This won't give you a "stripped down" version unless you decide to remove all the code from `src/components` too, but should provide a good starting point, especially for educational purposes.

**Comment by erichodges** [comment]
Ok cool, thanks. I'll look into that. :-)

**Comment by Vagr9K** [comment]
Closing the issue due to lack of activity.

Still, feel free to ask if you have any questions :)
