### ISSUE TITLE
yarn install fails, though npm install doesn't

### ISSUE THREAD

**Issue by Strangehill** [Vagr9K/gatsby-material-starter#34]
When running `new`, gatsby sees yarn present and it uses yarn over npm, failing after cloning the repo. The same applies to https://github.com/Vagr9K/gatsby-advanced-starter. So, while running `npm install` from the project directory fixes it, #33 does not in fact solve this issue because it's yarn.lock that needed the update all along.

`error An unexpected error occurred: "/Users/cog/material/node_modules/sharp: Command failed.`

**Comment by Vagr9K** [comment]
Thanks for the report!

Both repositories have now synced lockfiles and updated dependencies. Feel free to reopen is there is still in issue.
