### ISSUE TITLE
Not working on Internet Explorer

### ISSUE THREAD

**Issue by patrickabadi** [Vagr9K/gatsby-material-starter#40]
Hello,

First I have to commend you on a great site.  I'm using it on a personal blog and it's worked out quite well.  One of my readers mentioned that it wasn't working for him and after some back and forth I found out he was using Internet Explorer so I tried it and sure enough it was failing with some javascript .StartsWith errors.  (If you'd like I could track down the full list of errors)

Strangely your published demo starter site works fine but if I create a new gatsby starter site it does not, so I started going back several commits and found that it broke after the following:  2d758a0 

I also found this error on the advanced-material issues and tried applying it but it didn't seem to help:
https://github.com/Vagr9K/gatsby-advanced-starter/issues/17

I'm certainly not an expert in web technologies but I can make my way around js files, so if I can help in any way please let me know.

**Comment by Vagr9K** [comment]
> I also found this error on the advanced-material issues and tried applying it but it didn't seem to help

https://github.com/Vagr9K/gatsby-advanced-starter/issues/17 has already been integrated into `gatsby-material-starter` a while ago.

> I started going back several commits and found that it broke after the following: 2d758a0

I suspect there was something wrong with your testing methodology. robots.txt can't possibly break a browser, especially the JS code.

`master` branch works in IE11 just fine too. I even double checked it in a VM.

I'd suggest you to take a look at your own modifications.

**Comment by Vagr9K** [comment]
Should be fixed now!

**Comment by patrickabadi** [comment]
Thank you 👍
