### ISSUE TITLE
Why is pathPrefix required?

### ISSUE THREAD

**Issue by joshuapack** [Vagr9K/gatsby-material-starter#41]
I want to be on the root domain. However, pathPrefix is required. Adding "/" I believe maybe causing issues with other programs as I have seen references to url//post where forward slash is put in twice. I have changed those manually by removing the pathPrefix from those instances, but would be nice if it would work on root out of the box.

Any reason why pathPrefix is required?

**Comment by Vagr9K** [comment]
> I want to be on the root domain. However, pathPrefix is required.

PathPrefix is not required. If you want to be on root domain you need to set it as empty or "/".

> Adding "/" I believe maybe causing issues with other programs as I have seen references to url//post where forward slash is put in twice.

Sounds like a bug. Can you list them?

**Comment by ivanoats** [comment]
Would you accept a PR with a comment such as "DO NOT REMOVE" - this tripped me up when I removed the key/value pair in the object. It wasn't until I found this issue that I realized that it might be required to get the site working out of the box.

**Comment by Vagr9K** [comment]
This should no longer be a concern since `siteConfig` validators have been added.

Both an empty string and `/` are now valid `pathPrefixes`.
