### ISSUE TITLE
Hot reload not working?

### ISSUE THREAD

**Issue by adalberht** [Vagr9K/gatsby-material-starter#44]
Hi there,

I tried to fresh install the starter and made some changes on the component,  but I think the hot reload is not working?
Is there any issue with this or this is just me?

Thanks!

**Comment by Vagr9K** [comment]
Haven't seen an issue like this popup.

Considering your issue with `gatsby-advanced-starter` I'm going to assume npm freaks out here too for some reason. Refer to [my comment](https://github.com/Vagr9K/gatsby-advanced-starter/issues/37#issuecomment-406949818) for troubleshooting steps related to npm.

Also, which OS are you on?
I've seen file watch limits get overloaded on linux systems depending on running file indexers. 
Take a look at your `dmesg` and `journalctl` errors.

**Comment by adalberht** [comment]
Hi Vagr9K,

Yes, your assumption is correct here as well. It's an NPM problem. After upgrading my NPM and NodeJS to latest version there is no issue with the hot reloading.

And yes you are right I'm on linux systems, I'm using Xubuntu 18.04 LTS.

I'm amazed that you do really know a lot. Thank you very much for your help!
