### ISSUE TITLE
 Can't resolve 'gatsby-link'

### ISSUE THREAD

**Issue by Zeus-Iqd** [Vagr9K/gatsby-material-starter#46]
i use gatsby new myblog https://github.com/Vagr9K/gatsby-material-starter 
then cd myblog && npm install 
then npm run develop

**Comment by Vagr9K** [comment]
`gatsby-link` is not a dependency of the `v2` branch.

Make sure that you are using an up to date `gatbsy@next` to install the starter, or just use the other method described in documentation, since it pulls the correct versions automatically.

**Comment by Zeus-Iqd** [comment]
pleace update your documentation. For example:
gatsby new YourProjectName https://github.com/Vagr9K/gatsby-material-starter#v2
cd YourProjectName
npm run develop # or gatsby develop

**Comment by Vagr9K** [comment]
Sorry for the confusion.

`v2` branch has been merged into master for quite a while, and `gatsby-link` is not a dependency of it.

**Comment by Zeus-Iqd** [comment]
git clone https://github.com/Vagr9K/gatsby-material-starter YourProjectName # Clone the project
cd YourProjectname
rm -rf .git # So you can have your own changes stored in VCS.
npm install # or yarn install
npm run develop # or gatsby develop



This '.cache' file is automatically generated after execute npm run develop. You  make above command ,then you can understand my meaning. Please help me, thank you

**Comment by Zeus-Iqd** [comment]
You are right. Today, I use my mac. that will work.

**Comment by Vagr9K** [comment]
I'm assuming this was fixed.

Reopen if needed.
