### ISSUE TITLE
Reduce dependency on all files to siteConfig

### ISSUE THREAD

**Issue by Scot3004** [Vagr9K/gatsby-material-starter#49]
In some code places is required the module siteConfig but it's used just for take one value, i think is more reliable (for testing purposes) inject this as props depending on the cases

**Comment by Vagr9K** [comment]
The downside is that we will be stuck with a main component that has to relay `config` down to every single component.
Add `graphQuery` and `staticQuery` components to the list of props we already have to pass, and things get really messy.

It seems like `PostInfo` and `SocialLinks` can probably receive `config` as a prop without any problems though.
