### ISSUE TITLE
Add contributors guide

### ISSUE THREAD

**Issue by Scot3004** [Vagr9K/gatsby-material-starter#57]
For newcomer contributors is a good idea to have: contributing guide, issue template (look this feature of GitHub I love this) and pull request template.

The instructions are on the following links. 

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

https://blog.github.com/2018-05-02-issue-template-improvements/

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Try to make them all according your vision of the project

Postdata you can also use labels
https://help.github.com/articles/creating-a-label/

**Comment by Vagr9K** [comment]
I'm going to bee taking closer look at this and other issues this weekend.
