### ISSUE TITLE
Second post has an incorrect previous post

### ISSUE THREAD

**Issue by awaters1** [Vagr9K/gatsby-material-starter#61]
## Description

When viewing the second post the previous link points to the last post and not the first post

### Steps to reproduce

View the second post on site

### Expected result

Previous link should point to the first post

### Actual result

Previous link pointed to the last post

### Environment

  System:
    OS: Linux 4.18 Gentoo/Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 5.6.2 - /bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v8.11.3/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Firefox: 63.0.3
  npmPackages:
    gatsby: 2.0.55 => 2.0.55 
    gatsby-image: 2.0.20 => 2.0.20 
    gatsby-plugin-catch-links: 2.0.8 => 2.0.8 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-feed: 2.0.9 => 2.0.9 
    gatsby-plugin-google-analytics: 2.0.7 => 2.0.7 
    gatsby-plugin-lodash: 3.0.2 => 3.0.2 
    gatsby-plugin-manifest: 2.0.10 => 2.0.10 
    gatsby-plugin-netlify-cms: 3.0.7 => 3.0.7 
    gatsby-plugin-nprogress: 2.0.6 => 2.0.6 
    gatsby-plugin-offline: 2.0.17 => 2.0.17 
    gatsby-plugin-react-helmet: 3.0.2 => 3.0.2 
    gatsby-plugin-sass: 2.0.4 => 2.0.4 
    gatsby-plugin-sharp: 2.0.13 => 2.0.13 
    gatsby-plugin-sitemap: 2.0.2 => 2.0.2 
    gatsby-plugin-twitter: 2.0.7 => 2.0.7 
    gatsby-remark-autolink-headers: 2.0.11 => 2.0.11 
    gatsby-remark-copy-linked-files: 2.0.6 => 2.0.6 
    gatsby-remark-images: 3.0.0 => 3.0.0 
    gatsby-remark-prismjs: 3.0.3 => 3.0.3 
    gatsby-remark-relative-images: 0.2.0 => 0.2.0 
    gatsby-remark-responsive-iframe: 2.0.6 => 2.0.6 
    gatsby-source-filesystem: 2.0.8 => 2.0.8 
    gatsby-transformer-remark: 2.1.12 => 2.1.12 
    gatsby-transformer-sharp: 2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5

**Comment by Vagr9K** [comment]
Fixed in https://github.com/Vagr9K/gatsby-material-starter/pull/62 as per your PR.

Thank you!
