### ISSUE TITLE
How to adjust width of blog post

### ISSUE THREAD

**Issue by keepforever** [Vagr9K/gatsby-material-starter#63]
Hello, 

My question is very basic.  

Where do I adjust to make it so, when viewing a blog post (the full post and all the markdown) that the width of the material design Paper element that holds the markdown is the full width of the screen? 

Currently, on desktop, there is unused space on the left and right of the post markdown that I would like to use.  

Thanks, 
Brian

**Comment by Vagr9K** [comment]
Hey there!

The maximum width is controlled via class `post-page-contents` in https://github.com/Vagr9K/gatsby-material-starter/blob/master/src/templates/post.scss#L20.
It's set as `max-width: 752px;` by default.

The `div` element you're looking to style is: https://github.com/Vagr9K/gatsby-material-starter/blob/master/src/templates/post.jsx#L73.
