### ISSUE TITLE
GraphQL Error Unknown field `childImageSharp` on type `File`

### ISSUE THREAD

**Issue by rgstephens** [Vagr9K/gatsby-material-starter#66]
GraphQL Error Unknown field `childImageSharp` on type `File`

  file: /Users/.../.../src/components/PostCover/index.jsx

**Comment by Vagr9K** [comment]
I'm unable to reproduce neither in `develop` nor in `build` scenarios.

If you're still facing the issue, please open an issue and fill the bug report form with reproduction instructions.
