### ISSUE TITLE
Running npm audit fix breaks the post.jsx query

### ISSUE THREAD

**Issue by neonguru** [Vagr9K/gatsby-material-starter#67]
## Description

Just FYI for you that running `npm audit fix` breaks your build.

### Steps to reproduce

Follow steps in Issue submitted to gatsby:
https://github.com/gatsbyjs/gatsby/issues/13814

### Expected result

Project should build

### Actual result

Error occurs as described in above linked issue.

### Environment

$ gatsby info --clipboard

System:
OS: Windows 10
CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Binaries:
Yarn: 1.12.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.5.0 - D:\Program Files\nodejs\npm.CMD
Languages:
Python: 2.7.15
Browsers:
Edge: 42.17134.1.0
npmPackages:
gatsby: ^2.3.36 => 2.3.36
gatsby-image: 2.0.26 => 2.0.26
gatsby-plugin-catch-links: 2.0.9 => 2.0.9
gatsby-plugin-feed: 2.0.11 => 2.0.11
gatsby-plugin-google-analytics: 2.0.9 => 2.0.9
gatsby-plugin-lodash: 3.0.3 => 3.0.3
gatsby-plugin-manifest: 2.0.13 => 2.0.13
gatsby-plugin-netlify-cms: 3.0.9 => 3.0.9
gatsby-plugin-nprogress: 2.0.7 => 2.0.7
gatsby-plugin-offline: 2.0.21 => 2.0.21
gatsby-plugin-react-helmet: 3.0.5 => 3.0.5
gatsby-plugin-sass: 2.0.7 => 2.0.7
gatsby-plugin-sharp: ^2.0.35 => 2.0.35
gatsby-plugin-sitemap: 2.0.4 => 2.0.4
gatsby-plugin-twitter: 2.0.8 => 2.0.8
gatsby-remark-autolink-headers: 2.0.12 => 2.0.12
gatsby-remark-copy-linked-files: 2.0.8 => 2.0.8
gatsby-remark-images: 3.0.1 => 3.0.1
gatsby-remark-prismjs: 3.2.0 => 3.2.0
gatsby-remark-relative-images: ^0.2.2 => 0.2.2
gatsby-remark-responsive-iframe: 2.0.8 => 2.0.8
gatsby-source-filesystem: ^2.0.33 => 2.0.33
gatsby-transformer-remark: 2.2.0 => 2.2.0
gatsby-transformer-sharp: 2.1.10 => 2.1.10

error The system cannot find the path specified.

Error: The system cannot find the path specified.

envinfo.js:1 Function.e.exports.sync
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:4970

envinfo.js:1 Object.copySync
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:66948

envinfo.js:1 Object.t.writeSync.e [as writeSync]
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:48777

envinfo.js:1
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46934

envinfo.js:1 Promise.all.then.e
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46949

util.js:16 tryCatcher
[npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:2
3

promise.js:512 Promise._settlePromiseFromHandler
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:5
12:31

promise.js:569 Promise._settlePromise
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:5
69:18

promise.js:614 Promise._settlePromise0
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
14:10

promise.js:694 Promise._settlePromises
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
94:18

promise.js:638 Promise._fulfill
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
38:18

promise_array.js:126 PromiseArray._resolve
[npm]/[gatsby-cli]/[bluebird]/js/release/promise_arra
y.js:126:19

promise_array.js:144 PromiseArray._promiseFulfilled
[npm]/[gatsby-cli]/[bluebird]/js/release/promise_arra
y.js:144:14

promise.js:574 Promise._settlePromise
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:5
74:26

promise.js:614 Promise._settlePromise0
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
14:10

promise.js:694 Promise._settlePromises
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
94:18

error UNHANDLED REJECTION

Error: The system cannot find the path specified.

envinfo.js:1 Function.e.exports.sync
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:4970

envinfo.js:1 Object.copySync
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:66948

envinfo.js:1 Object.t.writeSync.e [as writeSync]
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:48777

envinfo.js:1
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46934

envinfo.js:1 Promise.all.then.e
[npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46949

util.js:16 tryCatcher
[npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:2
3

promise.js:512 Promise._settlePromiseFromHandler
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:5
12:31

promise.js:569 Promise._settlePromise
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:5
69:18

promise.js:614 Promise._settlePromise0
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
14:10

promise.js:694 Promise._settlePromises
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
94:18

promise.js:638 Promise._fulfill
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
38:18

promise_array.js:126 PromiseArray._resolve
[npm]/[gatsby-cli]/[bluebird]/js/release/promise_arra
y.js:126:19

promise_array.js:144 PromiseArray._promiseFulfilled
[npm]/[gatsby-cli]/[bluebird]/js/release/promise_arra
y.js:144:14

promise.js:574 Promise._settlePromise
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:5
74:26

promise.js:614 Promise._settlePromise0
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
14:10

promise.js:694 Promise._settlePromises
[npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:6
94:18

**Comment by neonguru** [comment]
referenced gatsby issue has been resolved:
https://github.com/gatsbyjs/gatsby/issues/13814

Looks like this project is using `setFieldsOnGraphQLNodeType` wrong or at least it doesn't work anymore.

Changes required to the gatsby-node.js solution in the referenced gatsby issue needs the following modification:

      const nextID = index + 1 < posts.length ? index + 1 : 0;
      const prevID = index - 1 >= 0 ? index - 1 : posts.length - 1;
      const previous = posts[prevID].node;
      const next = posts[nextID].node;

and the PostSuggestions handling can be simplified by passing a copy of the entire pageContext to it.

**Comment by Vagr9K** [comment]
Thanks for taking your time and reporting this!

**Comment by Vagr9K** [comment]
Thank you for taking your time and reporting this!

`npm audit fix` is mostly resolved with the dependency update in https://github.com/Vagr9K/gatsby-material-starter/commit/3e2ba2e73ead8e675a71f1c1d54cda0bc0fb3435.

Next/Previous post linking has also been streamlined in https://github.com/Vagr9K/gatsby-material-starter/commit/2f7bfa00f6a35d0371d8a2ec79446229c8a19fc7
