### ISSUE TITLE
gatsby-starter-material getting replicated?

### ISSUE THREAD

**Issue by vikaskyadav** [Vagr9K/gatsby-material-starter#7]
@Vagr9K I don't understand why gatsby-starter-material directory is getting nested recursively.

**Comment by Vagr9K** [comment]
It is a workaround to test `pathPrefix` via `gatsby serve`.
Since static files in `--path-prefix` build are pointing to `localhost/gatsby-starter-material/STATICFILE`, serving the directory while testing caused 404 errors.
Is it causing any issues?

**Comment by vikaskyadav** [comment]
Nah. I get it. It's all right. Just one thing bro, why don't you write a getting started guide. It really will be helpful for beginners. :)

**Comment by Vagr9K** [comment]
Everything that's needed to start using the starter is in the README. Including installation, configuration, features. Everything else is in [GatsbyJS docs](https://www.gatsbyjs.org/docs/). What are you specifically missing?

**Comment by Vagr9K** [comment]
Closing this.
If you have any suggestions about missing documentation, please open a separate issue.
