### ISSUE TITLE
Having trouble adding/implementing "gatsby-background-image"

### ISSUE THREAD

**Issue by keepforever** [Vagr9K/gatsby-material-starter#72]
I'm trying to use https://www.gatsbyjs.org/packages/gatsby-background-image/

It says the dependencies are `gatsby-transformer-sharp` and `gatsby-plugin-sharp`, which the **gatsby-material-starter** has.  

I was following a very recent tutorial on implementing and I seem to be having trouble querying the image. 

The code I implemented looks more or less like this: 
https://github.com/haydn5/Gatsby-Background-Image-Demo/blob/master/src/pages/index.js

But, when I try the query in the starter, it doesn't add anything to props. 

```js
export const pageQuery = graphql`
    query MyQuery {
        indexImage: file(relativePath: { eq: "crow_castle.jpg" }) {
            childImageSharp {
                fluid(maxWidth: 1800) {
                    ...GatsbyImageSharpFluid
                }
            }
        }
    }
`;
```

Any advice on how you would implement `gatsby-background-image` in this starter?

Thanks!

**Comment by keepforever** [comment]
Mainly, I'm just trying to add a "hero image" to a landing page where there's a large background image with welcome text overlayed and it seems gatsby isn't very friendly to just simply adding.

```jsx
<div style={{ backgroundImage: 'url("the/url")'}} > My Text </div>
```

If you would recommend another way of creating a hero image, I am open to suggestions and don't care if I use specifically `gatsby-background-image` or not.

**Comment by Vagr9K** [comment]
I'd recommend giving a shot to [`gatsby-image`](https://www.gatsbyjs.org/packages/gatsby-image/) directly instead.

Just make sure that you follow setup instructions and the plugin initialization order.

**Comment by Vagr9K** [comment]
The V3 release has made this issue obsolete.

Feel free to reopen if needed.
