### ISSUE TITLE
Documentation Request: How to create multiple "post" archives

### ISSUE THREAD

**Issue by diegovdc** [Vagr9K/gatsby-material-starter#8]
I would like to build a site that has for example a Blog section and a News section, could you please point me in the right direction to do that?

**Comment by Vagr9K** [comment]
Sections as in different pages or just parts of the same page?

You can create a special `frontmatter` variable that indicates the markdown file type. Either `blog` or `news`, then filter out `this.props.data.allMarkdownRemark.edges` in https://github.com/Vagr9K/gatsby-material-starter/blob/master/src/pages/index.jsx#L9 by the variable you have set, and then modify JSX accordingly to get multiple views of page sections (not only for blog posts via `PostListing`).

If you want to create separate page for listing news, then you'll have to modify https://github.com/Vagr9K/gatsby-material-starter/blob/master/gatsby-node.js#L69 `onCreatePages` to filter out news articles (just as it filters out tags) and create pages based on that.

Please note that I'm not aware of any starters that have support for multiple types of content. You might want to get yourself familiar with [Gatsby Node APIs](https://www.gatsbyjs.org/docs/node-apis/) and ask questions in Gatsby's Discord channel.
